language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install coveralls pep8 pep257
  - python setup.py install
script:
  - python setup.py test
after_success:
  - coverage run --source=negotiator2 setup.py test
  - coveralls
